version: '3.9'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: spring-algafood-api
    ports:
      - "5432:5432"
      